version: "3.7"

services: 
    task_manager_db:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD="348275723"
            - POSTGRES_USER="postgres"
            - POSTGRES_DB="TaskManager"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - .:/srv/src/
        ports: 
            - 8000:8000
            - 5432:5432
        depends_on: 
            - task_manager_db
        environment: 
            WAIT_HOSTS: task_manager_db:5432
volumes: 
    postgres_data:

