# Generated by Django 3.1.1 on 2020-09-30 21:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 1, 0, 17, 48, 94813), verbose_name='Время создания')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('Z', 'Запланированая'), ('V', 'В работе'), ('E', 'Завершенная')], max_length=1)),
                ('end_date', models.DateField(verbose_name='Планируемая дата завершения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
