# Generated by Django 3.1.1 on 2020-10-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskAPI', '0003_auto_20201007_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Действие', 'verbose_name_plural': 'Действия'},
        ),
    ]
